arch/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path(r'lookup/', views.lookup, name='arch-lookup'),
	path(r'pk/<int:pk>/', views.HintDetailByPK.as_view(), name='hint-detail-pk'),
	path(r'pk/<int:pk>/edit/', views.HintUpdateByPK.as_view(), name='hint-update-pk'),
	path(r'<str:puid>/edit/', views.ProblemUpdate.as_view(), name='problem-update'),
	path(r'<str:puid>/delete/', views.ProblemDelete.as_view(), name='problem-delete'),
	path(r'<str:puid>/<int:number>/', views.HintDetail.as_view(), name='hint-detail'),
	path(r'<str:puid>/add/', views.HintCreate.as_view(), name='hint-create'),
	path(r'<str:puid>/<int:number>/edit/', views.HintUpdate.as_view(), name='hint-update'),
	path(r'<str:puid>/<int:number>/delete/', views.HintDelete.as_view(), name='hint-delete'),
	path(r'<str:puid>/', views.HintList.as_view(), name='hint-list'),
	path(r'', views.ProblemCreate.as_view(), name='arch-index'),
]

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path(r'synopsis/', views.UnitGroupListView.as_view(), name='synopsis'),
	path(r'prefs/', views.UserProfileUpdateView.as_view(), name='profile'),
	path(r'unit/problems/<int:pk>/', views.unit_problems, name='view-problems'),
	path(r'unit/tex/<int:pk>/', views.unit_tex, name='view-tex'),
	path(r'unit/solutions/<int:pk>/', views.unit_solutions, name='view-solutions'),
	path(r'dismiss/email/', views.dismiss_emails, name='dismiss-emails'),
	path(r'dismiss/downloads/', views.dismiss_downloads, name='dismiss-downloads'),
]

dashboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path(r'portal/<int:student_id>/', views.portal, name='portal'),
	path(r'conquer/<int:student_id>/', views.submit_pset, name='submit-pset'),
	path(r'reconquer/<int:pk>/', views.resubmit_pset, name='resubmit-pset'),
	path(r'stats/<int:student_id>/', views.stats, name='stats'),
	path(r'achievements/', views.AchievementList.as_view(), name='achievements-listing'),
	path(r'foundlist/<int:pk>/', views.FoundList.as_view(), name='found-listing'),
	path(r'uploads/<int:student_id>/<int:unit_id>/', views.uploads, name='uploads'),
	path(r'editfile/<int:pk>/', views.UpdateFile.as_view(), name='editfile'),
	path(r'deletefile/<int:pk>/', views.DeleteFile.as_view(), name='delfile'),
	path(r'idlewarn/', views.idlewarn, name='idlewarn'),
	path(r'downloads/<int:pk>/', views.DownloadList.as_view(), name='downloads'),
	path(r'pset/<int:pk>/', views.PSetDetail.as_view(), name='pset'),
	path(r'past/', views.past, name='past'),
	path(r'past/<int:semester>/', views.past, name='past'),
	path(r'index/', views.index, name='index'),
	path(r'suggest/new', views.ProblemSuggestionCreate.as_view(), name='suggest-new'),
	path(
		r'suggest/<int:unit_id>/new/', views.ProblemSuggestionCreate.as_view(), name='suggest-new'
	),
	path(
		r'suggest/<int:pk>/edit/', views.ProblemSuggestionUpdate.as_view(), name='suggest-update'
	),
	path(r'suggest/list/', views.ProblemSuggestionList.as_view(), name='suggest-list'),
	path(r'leaderboard/', views.leaderboard, name='leaderboard'),
	path(r'palace/<int:student_id>/', views.PalaceList.as_view(), name='palace-list'),
	path(r'palace/evan/', views.AdminPalaceList.as_view(), name='admin-palace-list'),
	path(r'carve/<int:student_id>/', views.PalaceUpdate.as_view(), name='palace-update'),
	path(r'forge/<int:student_id>/', views.DiamondUpdate.as_view(), name='diamond-update'),
]

otisweb/urls.py
"""otisweb URL Configuration"""

import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView

from . import settings

assert settings.MEDIA_URL is not None

urlpatterns = [
	path(r'admin/', admin.site.urls),
	path(r'aincrad/', include('aincrad.urls')),
	path(r'arch/', include('arch.urls')),
	path(r'core/', include('core.urls')),
	path(r'dash/', include('dashboard.urls')),
	path(r'exams/', include('exams.urls')),
	path(r'markets/', include('markets.urls')),
	path(r'roster/', include('roster.urls')),
	path(r'hijack/', include('hijack.urls')),
	path(r'accounts/', include('allauth.urls')),
	path(r'notifications/', include('django_nyt.urls')),
	path(r'wiki/', include('wiki.urls')),
	path(r'fandom/', include('wikihaxx.urls')),
	path(r'__debug__/', include(debug_toolbar.urls)),
	path(
		r'robots.txt',
		TemplateView.as_view(template_name='robots.txt', content_type='text/plain'),
	),
	path(r'favicon.ico', RedirectView.as_view(url="https://web.evanchen.cc/icons/favicon.ico")),
	path(r'', RedirectView.as_view(pattern_name='index')),
] + static(
	settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # type: ignore

if settings.DEBUG:
	admin.site.site_header = '127.0.0.1'
	admin.site.index_title = 'Switchboard'
	admin.site.site_title = 'otis@localhost'
else:
	admin.site.site_header = 'OTIS Headquarters'
	admin.site.index_title = 'GM Panel'
	admin.site.site_title = 'OTIS HQ'

wikihaxx/urls.py
from django.urls.conf import path

from . import views

urlpatterns = [
	path(r'problem/<str:puid>/', views.problem, name='wiki-problem'),
	path(r'unitgroup/<int:pk>/', views.unitgroup, name='wiki-unitgroup'),
]

dashboard/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import datetime
import os
from hashlib import sha256

from core.models import Semester, Unit, UnitGroup
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.files.base import File
from django.core.validators import FileExtensionValidator, MaxValueValidator, MinValueValidator, RegexValidator  # NOQA
from django.db import models
from django.urls import reverse_lazy
from roster.models import Student


def validate_at_most_1mb(f: File):
	if f.size > 1024 * 1024:
		raise ValidationError("At most 1MB allowed")


def content_file_name(instance: 'UploadedFile', filename: str) -> str:
	now = datetime.datetime.now()
	return os.path.join(
		instance.category, instance.owner.username, now.strftime("%Y-%m-%d-%H%M%S"), filename
	)


class UploadedFile(models.Model):
	"""An uploaded file, for example a transcript or homework solutions."""
	CHOICES = (
		("psets", "PSet Submission"), ("scripts", "Transcript"), ("notes", "Notes / Comments"),
		("misc", "Miscellaneous")
	)
	benefactor = models.ForeignKey(
		Student, on_delete=models.CASCADE, help_text="The student for which this file is meant"
	)
	owner = models.ForeignKey(
		User, on_delete=models.CASCADE, help_text="The user who uploaded the file"
	)
	category = models.CharField(
		max_length=10, choices=CHOICES, help_text="What kind of file this is"
	)
	description = models.CharField(
		max_length=250, blank=True, help_text="Optional description of the file"
	)
	content = models.FileField(
		help_text="The file itself",
		upload_to=content_file_name,
		validators=[FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'tex', 'png', 'jpg'])]
	)
	unit = models.ForeignKey(
		Unit,
		null=True,
		blank=True,
		on_delete=models.SET_NULL,
		help_text="The unit for which this file is associated"
	)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.filename

	@property
	def filename(self):
		return os.path.basename(self.content.name)

	@property
	def url(self):
		return self.content.url

	class Meta:
		ordering = ('-created_at', )

	def get_absolute_url(self):
		return self.url


def download_file_name(instance: 'SemesterDownloadFile', filename: str) -> str:
	return os.path.join("global", str(instance.semester.id), filename)


class SemesterDownloadFile(models.Model):
	semester = models.ForeignKey(
		Semester,
		on_delete=models.CASCADE,
		help_text="The semester to which the file is associated"
	)
	description = models.CharField(
		max_length=250, blank=True, help_text="Optional description of the file"
	)
	content = models.FileField(
		help_text="The file itself",
		upload_to=download_file_name,
	)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return os.path.basename(self.content.name)

	class Meta:
		ordering = ('-created_at', )

	def get_absolute_url(self):
		return self.content.url


class PSet(models.Model):
	resubmitted = models.BooleanField(
		help_text="Tracks if problem set resubmitted", default=False
	)
	approved = models.BooleanField(
		help_text="Whether the latest version of the problem set has been checked off",
		default=False
	)
	student = models.ForeignKey(
		Student, help_text="The student attached to this", on_delete=models.CASCADE
	)
	unit = models.ForeignKey(
		Unit,
		help_text="The unit you want to submit for",
		on_delete=models.SET_NULL,
		null=True,
	)
	upload = models.ForeignKey(
		UploadedFile,
		help_text="The associated upload file for this problem set",
		on_delete=models.CASCADE,
		null=True,
		blank=False,
	)
	hours = models.FloatField(
		help_text="Number of hours spent on this problem set",
		verbose_name="Hours spent (estimate)",
		null=True,
		blank=True,
		validators=[
			MinValueValidator(0),
			MaxValueValidator(200),
		],
	)
	clubs = models.IntegerField(
		help_text="Total number of clubs that you solved (including 1♣ if feedback written)",
		verbose_name="Total ♣ earned",
		null=True,
		blank=True,
		validators=[
			MinValueValidator(0),
			MaxValueValidator(200),
		]
	)
	eligible = models.BooleanField(
		default=True, help_text="Whether to count this for leveling up"
	)
	feedback = models.TextField(
		verbose_name="Feedback on problem set, worth [1♣]",
		help_text="Any other feedback about the problem set",
		blank=True
	)
	next_unit_to_unlock = models.ForeignKey(
		Unit,
		help_text="The unit you want to work on next (leave blank for none)",
		on_delete=models.SET_NULL,
		null=True,
		blank=True,
		related_name='unblocking_psets',
	)
	special_notes = models.TextField(
		help_text="If there's anything you need to say before we proceed", blank=True
	)

	def __str__(self):
		return f'{self.student.name} submits {self.unit}'

	def get_absolute_url(self):
		return reverse_lazy('pset', args=(self.pk, ))


class ProblemSuggestion(models.Model):
	user = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		help_text="User who suggested the problem.",
	)
	unit = models.ForeignKey(
		Unit, on_delete=models.CASCADE, help_text="The unit to suggest the problem for."
	)
	weight = models.PositiveSmallIntegerField(
		choices=((2, 2), (3, 3), (5, 5), (9, 9)), null=True, blank=True
	)
	source = models.CharField(
		max_length=60, help_text="Source of the problem, e.g. `Shortlist 2018 A7`."
	)
	description = models.CharField(
		max_length=100,
		help_text="A one-line summary of problem, e.g. `Inequality with cube roots`."
	)
	statement = models.TextField(help_text="Statement of the problem, in LaTeX.")
	solution = models.TextField(help_text="Solution to the problem, in LaTeX.")
	comments = models.TextField(help_text="Any extra comments.", blank=True)
	acknowledge = models.BooleanField(
		help_text="Acknowledge me for this contribution. "
		"(Uncheck for an anonymous contribution.)",
		default=True
	)

	resolved = models.BooleanField(default=False, help_text="Whether staff has processed this.")
	eligible = models.BooleanField(
		default=True, help_text="Whether this suggestion is eligible for spades."
	)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self) -> str:
		return f"{self.user.username} suggested {self.source} for {self.unit.group}"


def achievement_image_file_name(instance: 'Achievement', filename: str) -> str:
	kludge = (settings.SECRET_KEY or '') + '_otis_' + str(instance.pk)
	h = sha256(kludge.encode('ascii')).hexdigest()[0:18]
	return os.path.join('badges', h + os.path.splitext(filename)[-1])


class Achievement(models.Model):
	code = models.CharField(
		max_length=96,
		unique=True,
		null=True,
		validators=[
			RegexValidator(regex=r'^[a-f0-9]{24,25}$', message='24-25 char hex string'),
		],
	)
	name = models.CharField(max_length=128, help_text="Name of the achievement")
	image = models.ImageField(
		upload_to=achievement_image_file_name,
		help_text="Image for the obtained achievement, at most 1MB.",
		null=True,
		blank=True,
		validators=[validate_at_most_1mb],
	)
	description = models.TextField(
		help_text="Text shown beneath this achievement for students who obtain it."
	)
	active = models.BooleanField(help_text="Whether the code is active right now", default=True)
	diamonds = models.SmallIntegerField(
		default=1, help_text="Number of diamonds for this achievement"
	)
	creator = models.ForeignKey(
		Student,
		on_delete=models.CASCADE,
		null=True,
		blank=True,
		help_text="Student who owns this achievement"
	)

	def __str__(self) -> str:
		return str(self.name)


class Level(models.Model):
	threshold = models.IntegerField(unique=True, help_text="The number of the level")
	name = models.CharField(max_length=128, help_text="The name of the level")

	def __str__(self):
		return f'Level {self.threshold}: {self.name}'


class AchievementUnlock(models.Model):
	user = models.ForeignKey(
		User, on_delete=models.CASCADE, help_text="The user who unlocked the achievement"
	)
	achievement = models.ForeignKey(
		Achievement, on_delete=models.CASCADE, help_text="The achievement that was obtained"
	)
	timestamp = models.DateTimeField(
		auto_now_add=True, help_text='The time the achievement was granted'
	)

	def __str__(self) -> str:
		return self.timestamp.strftime('%c')

	class Meta:
		unique_together = (
			'user',
			'achievement',
		)


class QuestComplete(models.Model):
	student = models.ForeignKey(
		Student, on_delete=models.CASCADE, help_text="Student obtaining this reward"
	)
	title = models.CharField(max_length=160, help_text="A summary")
	spades = models.PositiveSmallIntegerField(help_text="The number of spades granted")
	timestamp = models.DateTimeField(
		auto_now_add=True, help_text='The time the achievement was granted'
	)

	CATEGORY_CHOICES = (
		("PR", "Pull request"),
		("BR", "Bug report"),
		("WK", "Wiki bonus"),
		("US", "USEMO Score"),
		("UG", "USEMO Grading"),
		("MS", "Miscellaneous"),
	)
	category = models.CharField(
		max_length=4,
		choices=CATEGORY_CHOICES,
		default="MS",
	)

	def __str__(self) -> str:
		return self.title + ' ' + self.timestamp.strftime('%c')


class BonusLevel(models.Model):
	group = models.OneToOneField(UnitGroup, on_delete=models.CASCADE)
	level = models.PositiveSmallIntegerField(help_text="Level to spawn at")
	active = models.BooleanField(default=True)

	def __str__(self) -> str:
		return f"Lv. {self.level} Bonus ({'active' if self.active else 'inert'})"


class BonusLevelUnlock(models.Model):
	timestamp = models.DateTimeField(auto_now_add=True)
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	bonus = models.ForeignKey(BonusLevel, on_delete=models.CASCADE)

	def __str__(self) -> str:
		return self.timestamp.isoformat()


def palace_image_file_name(instance: 'PalaceCarving', filename: str) -> str:
	return os.path.join('palace', filename)


class PalaceCarving(models.Model):
	student = models.OneToOneField(Student, on_delete=models.CASCADE, null=True, blank=True)
	display_name = models.CharField(
		max_length=128,

dashboard/forms.py
from django import forms
from django.core.validators import FileExtensionValidator

from dashboard.models import PSet, UploadedFile


class NewUploadForm(forms.ModelForm):
	class Meta:
		model = UploadedFile
		fields = ('category', 'content', 'description')
		widgets = {
			'description': forms.Textarea(attrs={
				'cols': 40,
				'rows': 2
			}),
		}
		help_texts = {
			'content': "",
		}


pset_file_validator = FileExtensionValidator(
	allowed_extensions=['pdf', 'txt', 'tex', 'png', 'jpg']
)


class PSetSubmitForm(forms.ModelForm):
	content = forms.FileField(
		help_text="The file itself",
		validators=[
			pset_file_validator,
		],
	)

	class Meta:
		model = PSet
		fields = (
			'unit',
			'clubs',
			'hours',
			'feedback',
			'special_notes',
			'next_unit_to_unlock',
		)


class PSetResubmitForm(forms.ModelForm):
	content = forms.FileField(
		help_text="The file itself",
		validators=[
			pset_file_validator,
		],
	)

	class Meta:
		model = PSet
		fields = (
			'clubs',
			'hours',
			'feedback',
			'special_notes',
		)


class DiamondsForm(forms.Form):
	code = forms.CharField(label="", max_length=64, required=True)

dashboard/templates/dashboard/achievement_form.html
{% extends 'layout.html' %}
{% block title %}Forging a diamond{% endblock %}

{% block layout-content %}
<p><a href="{% url 'palace-list' student.id %}">Back to Ruby Palace</a></p>
<hr />
{% include "generic-form.html" %}

{% endblock %}

dashboard/templates/dashboard/back_link.html
<ul>
	<li><a href="{% url "portal" student.id %}">Back to portal</a></li>
</ul>

dashboard/templates/dashboard/diamond_list.html
{% extends 'layout.html' %}
{% block title %}Achievements Listing{% endblock %}

{% block layout-content %}
<div class="list-group">
	{% for achievement in achievement_list %}
	<div class="list-group-item container" {% if achievement.obtained %} style="background-color: #ddffdd;" {% else %} style="background-color: #ffddff;" {% endif %}>
		<div class="d-flex justify-content-between">
			<span style="color: #9c1421;">
				{% if achievement.num_found > 0 %}
				{{ achievement.diamonds }}♦️
				{% else %}
				???
				{% endif %}
			</span>
		</div>
		{% if achievement.num_found > 0 %}
		<span {% if not achievement.obtained %} style="filter: grayscale(100%) opacity(40%);" {% endif %}>
			{% if achievement.image %}
			<img width="64px" style="float: right;" src="{{ achievement.image.url }}" />
			{% else %}
			<div width="64px" style="float: right;">No image</div>
			{% endif %}
		</span>
		<p>Found by
			{% if request.user.is_staff %}
			<a href="{% url "found-listing" achievement.pk %}">
				<b>{{ achievement.num_found }} user{{ achievement.num_found|pluralize }}</b>.
			</a>
			{% else %}
			<b>{{ achievement.num_found }} user{{ achievement.num_found|pluralize }}</b>.
			{% endif %}
		</p>
		{% else %}
		<span style="float: right; font-size:64px;">❓</span>
		<p>Nobody has found this one yet!</p>
		{% endif %}
		{% if achievement.obtained %}
		<p>You found this achievement already.</p>
		{% else %}
		<p>You have not found this achievement yet.</p>
		{% endif %}
	</div>
	{% endfor %}
</div>
{% endblock %}

dashboard/templates/dashboard/download_list.html
{% extends 'layout.html' %}
{% block title %}Downloads {% endblock %}
{% block layout-content %}

<p>Here are the downloads available for this year:</p>
<ul>
	{% for file in object_list %}
	<li>
		<p>
			<b><a href="{{ file.content.url }}">{{ file }}</a></b>
			{% if file.description %} &mdash; {{file.description}}{% endif %}
			<br />
			<small>Uploaded at {{ file.created_at|date:"r" }}.
				{% if request.user.is_superuser %}
				<a href="{% url "admin:dashboard_semesterdownloadfile_change" file.id %}">
					(edit)</a>
				{% endif %}
			</small>
		</p>
	</li>
	{% endfor %}
</ul>

{% endblock %}

dashboard/templates/dashboard/idlewarn.html
{% extends 'layout.html' %}
{% load static %}
{% load otis_extras %}

{% block layout-content %}
<p>This is <i>Idle-Warn</i>,
	where you can find a list of students
	who have yet to submit the first problem set,
	or have not submitted a problem set for a while.
	Be gentle! Don't be the bad guy.</p>

<table class="table">
	<thead class="table-dark">
		<tr>
			<th>Lv</th>
			<th>Name</th>
			<th>Last pset</th>
			<th>Last login</th>
			<th>Units</th>
		</tr>
	</thead>

	<tbody>
		{% for row in rows %}
		{% with student=row.student %}
		<tr>
			<td>Lv. {{ row.level }}</td>
			<td><a title="{{ student.name }}" href="{% url "portal" student.id %}" class="tooltip-link">
					{{ student.user.email }}</a></td>
			{% if student.latest_pset %}
			<td class="text-end">{{ row.days_since_last_pset|floatformat:2 }} days</td>
			{% else %}
			<td>∞</td>
			{% endif%}
			<td class="text-end">{{ row.days_since_last_seen|floatformat:2 }} days</td>
			<td class="text-end">{{ student.num_psets|default_if_none:0 }}</td>
		</tr>
		{% endwith %}
		{% endfor %}
	</tbody>
</table>

<p>This list was generated {% now "r" %}.</p>
{% endblock %}

dashboard/templates/dashboard/problemsuggestion_form.html
{% extends 'layout.html' %}
{% block title %}Problem Suggestion{% endblock %}
{% block layout-content %}

<p><a href="{% url "suggest-list" %}">
		⬅️ List all suggestions by you.</a></p>

<p>Thank you for suggesting problems for OTIS!
	Your contributions are appreciated.</p>

<p>Some legalese notes:</p>
<ul>
	<li><strong>You should submit a solution</strong>.
		If you don't, I might get to solving the problem eventually,
		but let's be real, there's at least 200 problems on my
		someone-told-me-to-do-it list.</li>
	<li><strong>You cannot copy the wording of
			someone else's solution</strong>, at least not without permission.
		However, it's okay if the ideas in the solution are not your own,
		or someone else found an isomorphic solution to yours.
	</li>
	<li>By submitting, you are granting Evan permission to use, edit, or adapt
		anything you submit for OTIS,
		or any other math-olympiad-related purposes.</li>
	<li>On the other hand, you retain copyright/ownership of your writing,
		so you can also use it for whatever you want elsewhere.</li>
</ul>

<p>One quick word of advice: if you are suggesting a problem
	from a fairly well-known source (e.g. IMO Shortlist),
	there is a decent chance Evan might have done the problem already
	and placed it on some unit. So it might be worth double-checking first.</p>

{% load crispy_forms_tags %}
<form action="{{ request.path }}" method="post" class="form">
	{% csrf_token %}

	{% if form.non_field_errors %}
	<div class="alert alert-danger" role="alert">
		<p>The following errors were thrown:</p>
		<ul>
			{% for err in form.non_field_errors %}
			<li>{{ err }}</li>
			{% endfor %}
		</ul>
	</div>
	{% endif %}

	<table class="table form-table">
		<tr>
			<td> {{ form.weight|as_crispy_field }} </td>
			<td> {{ form.unit|as_crispy_field }} </td>
		</tr>
		<tr>
			<td colspan="2">{{ form.source|as_crispy_field }}</td>
		</tr>
		<tr>
			<td colspan="2">{{ form.description|as_crispy_field }}</td>
		</tr>
		<tr>
			<td colspan="2">{{ form.statement|as_crispy_field }}</td>
		</tr>
		<tr>
			<td colspan="2">
				<div id="statement_render"></div>
			</td>
		</tr>
		<tr>
			<td colspan="2">{{ form.solution|as_crispy_field }}</td>
		</tr>
		<tr>
			<td colspan="2">
				<div id="solution_render"></div>
			</td>
		</tr>
		<tr>
			<td colspan="2">{{ form.comments|as_crispy_field }}</td>
		</tr>
		<tr>
			<td colspan="2">{{ form.acknowledge|as_crispy_field }}</td>
		</tr>
		<tr>
			<td><button type="submit" class="btn btn-success">Submit</button></td>
			<td>
				<button id="render-toggle" class="btn btn-info">Disable instant TeX</button>
			</td>
		</tr>
	</table>

	{% endblock %}

	{% block css %}
	<style type="text/css">
		#solution_render,
		#statement_render {
			color: blue;
			font-family: sans-serif;
		}
	</style>
	{% endblock %}
	{% block scripts %}
	<script type="text/javascript">
		$(document).ready(function() {
			$("#id_unit").chosen();
			let autorender_enabled = true;
			let render_enabled = true;
			let mathjaxLoaded = false;

			$("#render-toggle").click(function(e) {
				e.preventDefault();
				if (render_enabled && autorender_enabled) {
					render_enabled = true;
					autorender_enabled = false;
					$("#render-toggle")
						.addClass("btn-danger")
						.removeClass("btn-info")
						.text("Turn off LaTeX");
				} else if (render_enabled) {
					render_enabled = false;
					$("#render-toggle")
						.addClass("btn-primary")
						.removeClass("btn-danger")
						.text("Enable instant-TeX");
				} else {
					render_enabled = true;
					autorender_enabled = true;
					$("#render-toggle")
						.addClass("btn-info")
						.removeClass("btn-primary")
						.text("Disable instant-TeX");
				}
				render_statement();
				render_solution();
			});

			$("#id_statement").on("input", (e) => {
				if (!autorender_enabled || !render_enabled) return;
				$("#statement_render").text(e.target.value);
				MathJax.typesetPromise([document.querySelector("#statement_render")]);
			});

			$("#id_solution").on("input", (e) => {
				if (!autorender_enabled || !render_enabled) return;
				$("#solution_render").text(e.target.value);
				MathJax.typesetPromise([document.querySelector("#solution_render")]);
			});

			function render_statement() {
				if (!render_enabled) return;
				if (!mathjaxLoaded) console.warn("MathJax has not finished loading yet.");
				$("#statement_render").text($("#id_statement").val());
				MathJax.typeset([document.querySelector("#statement_render")]);
			}

			function render_solution() {
				if (!render_enabled) return;
				if (!mathjaxLoaded) console.warn("MathJax has not finished loading yet.");
				$("#solution_render").text($("#id_solution").val());
				MathJax.typeset([document.querySelector("#solution_render")]);
			}

			$("#id_statement").blur(render_statement);
			$("#id_solution").blur(render_solution);

			window.MathJaxLoaded.then(() => {
				mathjaxLoaded = true;
				render_statement();
				render_solution();
			});
		});
	</script>
	{% endblock %}