arch/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path(r'lookup/', views.lookup, name='arch-lookup'),
	path(r'pk/<int:pk>/', views.HintDetailByPK.as_view(), name='hint-detail-pk'),
	path(r'pk/<int:pk>/edit/', views.HintUpdateByPK.as_view(), name='hint-update-pk'),
	path(r'<str:puid>/edit/', views.ProblemUpdate.as_view(), name='problem-update'),
	path(r'<str:puid>/delete/', views.ProblemDelete.as_view(), name='problem-delete'),
	path(r'<str:puid>/<int:number>/', views.HintDetail.as_view(), name='hint-detail'),
	path(r'<str:puid>/add/', views.HintCreate.as_view(), name='hint-create'),
	path(r'<str:puid>/<int:number>/edit/', views.HintUpdate.as_view(), name='hint-update'),
	path(r'<str:puid>/<int:number>/delete/', views.HintDelete.as_view(), name='hint-delete'),
	path(r'<str:puid>/', views.HintList.as_view(), name='hint-list'),
	path(r'', views.ProblemCreate.as_view(), name='arch-index'),
]

otisweb/urls.py
"""otisweb URL Configuration"""

import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView

from . import settings

assert settings.MEDIA_URL is not None

urlpatterns = [
	path(r'admin/', admin.site.urls),
	path(r'aincrad/', include('aincrad.urls')),
	path(r'arch/', include('arch.urls')),
	path(r'core/', include('core.urls')),
	path(r'dash/', include('dashboard.urls')),
	path(r'exams/', include('exams.urls')),
	path(r'markets/', include('markets.urls')),
	path(r'roster/', include('roster.urls')),
	path(r'hijack/', include('hijack.urls')),
	path(r'accounts/', include('allauth.urls')),
	path(r'notifications/', include('django_nyt.urls')),
	path(r'wiki/', include('wiki.urls')),
	path(r'fandom/', include('wikihaxx.urls')),
	path(r'__debug__/', include(debug_toolbar.urls)),
	path(
		r'robots.txt',
		TemplateView.as_view(template_name='robots.txt', content_type='text/plain'),
	),
	path(r'favicon.ico', RedirectView.as_view(url="https://web.evanchen.cc/icons/favicon.ico")),
	path(r'', RedirectView.as_view(pattern_name='index')),
] + static(
	settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # type: ignore

if settings.DEBUG:
	admin.site.site_header = '127.0.0.1'
	admin.site.index_title = 'Switchboard'
	admin.site.site_title = 'otis@localhost'
else:
	admin.site.site_header = 'OTIS Headquarters'
	admin.site.index_title = 'GM Panel'
	admin.site.site_title = 'OTIS HQ'

wikihaxx/urls.py
from django.urls.conf import path

from . import views

urlpatterns = [
	path(r'problem/<str:puid>/', views.problem, name='wiki-problem'),
	path(r'unitgroup/<int:pk>/', views.unitgroup, name='wiki-unitgroup'),
]

arch/models.py
from pathlib import Path
from typing import Optional

import reversion
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse_lazy


# Create your models here.
@reversion.register()
class Problem(models.Model):
	id = models.AutoField(primary_key=True)
	puid = models.CharField(
		max_length=24,
		help_text="Unique problem identifier, as printed in OTIS handout.",
		unique=True,
		verbose_name="PUID",
		validators=[
			RegexValidator(
				regex=r'[A-Z0-9]+', message="Only uppercase letters and digits appear in PUID's."
			)
		],
	)
	aops_url = models.URLField(
		max_length=128,
		help_text="URL to problem on AoPS. Include HTTPS.",
		blank=True,
		verbose_name="AoPS URL",
	)

	def __str__(self) -> str:
		return self.puid

	def get_absolute_url(self):
		return reverse_lazy("hint-list", args=(self.puid, ))

	def get_statement(self) -> Optional[str]:
		if settings.PATH_STATEMENT_ON_DISK is None:
			return None
		statement_path = Path(settings.PATH_STATEMENT_ON_DISK) / (self.puid + '.html')
		if statement_path.exists() and statement_path.is_file():
			return statement_path.read_text()
		return None

	class Meta:
		ordering = ('puid', )


@reversion.register()
class Hint(models.Model):
	id = models.AutoField(primary_key=True)
	problem = models.ForeignKey(
		Problem, on_delete=models.CASCADE, help_text=r"The container of the current hint."
	)
	keywords = models.CharField(
		max_length=255,
		default='',
		blank=True,
		help_text=r"A comma-separated list of keywords that a solver could look at "
		"to help them guess whether the hint is relevant or not. "
		"These are viewable immediately, so no spoilers here. "
		"Examples are 'setup', 'advice', 'answer confirmation', 'nudge',"
		"'main idea', 'solution set', 'converse direction', 'construction', etc. "
		"Not all hints go well with keywords, so you can leave this "
		"blank if you can't think of anything useful to write."
	)
	number = models.PositiveIntegerField(
		help_text=r"A number from 0 to 100 used to indicate an "
		r"ordering for the hints. "
		r"Here a number 0 means a hint given to someone at the very start "
		r"whereas 100 means a hint given to someone who was read all previous hints "
		r"or is close to the end of the problem. "
		r"Do your best to make up an extrapolation for everything in between. "
		r"A good idea is to give a sequence of hints with nearby numbers, say 20/21/22, "
		r"each of which elaborates on the previous hint."
	)
	content = models.TextField(help_text="The content of the hint. LaTeX rendering is okay.")

	class Meta:
		unique_together = (
			'problem',
			'number',
		)

	def __str__(self):
		return f"Hint {self.number}% for {self.problem}"

	def puid(self) -> str:
		return self.problem.puid

	def get_absolute_url(self):
		return reverse_lazy(
			"hint-detail", args=(
				self.problem.puid,
				self.number,
			)
		)

arch/forms.py
from django import forms

from .models import Hint, Problem


class HintUpdateFormWithReason(forms.ModelForm):
	reason = forms.CharField(max_length=255, help_text="Reason for editing.", required=False)

	class Meta:
		model = Hint
		fields = (
			'problem',
			'number',
			'keywords',
			'content',
			'reason',
		)


class ProblemUpdateForm(forms.ModelForm):
	class Meta:
		model = Problem
		fields = ('aops_url', )


class ProblemSelectForm(forms.Form):
	problem = forms.ModelChoiceField(queryset=Problem.objects.all())

arch/views.py
from typing import Any, ClassVar, Dict

import reversion
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from reversion.views import RevisionMixin
from roster.models import Student

from arch.forms import ProblemSelectForm

from .forms import HintUpdateFormWithReason
from .models import Hint, Problem

ContextType = Dict[str, Any]


class ExistStudentRequiredMixin(LoginRequiredMixin):
	def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any):
		if not request.user.is_authenticated:
			return super().dispatch(request, *args, **kwargs)
		assert isinstance(request.user, User)
		if not Student.objects.filter(user=request.user).exists() and not request.user.is_staff:
			raise PermissionDenied(
				'You have to be enrolled in at least one semester '
				'of OTIS to use the ARCH system'
			)
		else:
			return super().dispatch(request, *args, **kwargs)


class HintObjectView:
	kwargs: ClassVar[Dict[str, Any]] = {}

	def get_object(self, queryset: QuerySet[Hint] = None) -> Hint:
		if queryset is None:
			queryset = self.get_queryset()  # type: ignore
		return get_object_or_404(
			queryset, problem__puid=self.kwargs['puid'], number=self.kwargs['number']
		)


class ProblemObjectView:
	kwargs: ClassVar[Dict[str, Any]] = {}

	def get_object(self, queryset: QuerySet[Problem] = None) -> Problem:
		if queryset is None:
			queryset = self.get_queryset()  # type: ignore
		return get_object_or_404(queryset, puid=self.kwargs['puid'])


class HintList(ExistStudentRequiredMixin, ListView[Hint]):
	context_object_name = "hint_list"

	def get_queryset(self):
		self.problem = get_object_or_404(Problem, **self.kwargs)
		return Hint.objects.filter(problem=self.problem).order_by('number')

	def get_context_data(self, **kwargs: Dict[Any, Any]):
		context = super().get_context_data(**kwargs)
		context['problem'] = self.problem
		context['statement'] = self.problem.get_statement
		return context


class HintDetail(HintObjectView, ExistStudentRequiredMixin, DetailView[Hint]):
	context_object_name = "hint"
	model = Hint


class HintDetailByPK(ExistStudentRequiredMixin, DetailView[Hint]):
	context_object_name = "hint"
	model = Hint


class HintUpdate(
	HintObjectView, ExistStudentRequiredMixin, RevisionMixin,
	UpdateView[Hint, HintUpdateFormWithReason]
):
	context_object_name = "hint"
	model = Hint
	form_class = HintUpdateFormWithReason
	object: ClassVar[Hint] = Hint()

	def form_valid(self, form: HintUpdateFormWithReason) -> HttpResponse:
		reversion.set_comment(form.cleaned_data['reason'] or form.cleaned_data['content'])
		return super().form_valid(form)

	def get_context_data(self, **kwargs: Any) -> ContextType:
		context = super().get_context_data(**kwargs)
		context['problem'] = self.object.problem
		return context

	def get_success_url(self):
		return self.object.get_absolute_url()


class HintUpdateByPK(
	ExistStudentRequiredMixin, RevisionMixin, UpdateView[Hint, HintUpdateFormWithReason]
):
	context_object_name = "hint"
	model = Hint
	form_class = HintUpdateFormWithReason
	object: ClassVar[Hint] = Hint()

	def form_valid(self, form: HintUpdateFormWithReason) -> HttpResponse:
		reversion.set_comment(form.cleaned_data['reason'] or form.cleaned_data['content'])
		return super().form_valid(form)

	def get_context_data(self, **kwargs: Any) -> ContextType:
		context = super().get_context_data(**kwargs)
		context['problem'] = self.object.problem
		return context

	def get_success_url(self):
		return self.object.get_absolute_url()


class ProblemUpdate(
	ProblemObjectView, ExistStudentRequiredMixin, RevisionMixin,
	UpdateView[Problem, BaseModelForm[Problem]]
):
	context_object_name = "problem"
	model = Problem
	fields = (
		'puid',
		'aops_url',
	)

	def get_context_data(self, **kwargs: Any):
		context = super().get_context_data(**kwargs)
		context['num_problems'] = Problem.objects.all().count()
		context['num_hints'] = Hint.objects.all().count()
		return context

	def get_success_url(self) -> str:
		return self.object.get_absolute_url()  # type: ignore


class HintCreate(
	ExistStudentRequiredMixin, RevisionMixin, CreateView[Hint, BaseModelForm[Hint]]
):
	context_object_name = "hint"
	fields = (
		'problem',
		'number',
		'keywords',
		'content',
	)
	model = Hint

	def get_initial(self):
		initial = super(HintCreate, self).get_initial()
		initial = initial.copy()
		initial['problem'] = Problem.objects.get(puid=self.kwargs['puid'])
		return initial


class HintDelete(HintObjectView, ExistStudentRequiredMixin, RevisionMixin, DeleteView):
	context_object_name = "hint"
	model = Hint
	object: ClassVar[Hint] = Hint()

	def get_success_url(self):
		return reverse_lazy("hint-list", args=(self.object.problem.puid, ))


class ProblemDelete(ProblemObjectView, ExistStudentRequiredMixin, RevisionMixin, DeleteView):
	context_object_name = "problem"
	model = Problem
	object: ClassVar[Problem] = Problem()

	def get_success_url(self):
		return reverse_lazy("arch-index")


# this is actually the index page as well :P bit of a hack I guess...
class ProblemCreate(
	ExistStudentRequiredMixin, RevisionMixin, CreateView[Problem, BaseModelForm[Problem]]
):
	context_object_name = "problem"
	fields = ('puid', )
	model = Problem
	template_name = 'arch/index.html'

	def get_context_data(self, **kwargs: Any):
		context = super().get_context_data(**kwargs)
		context['lookup_form'] = ProblemSelectForm()
		context['num_problems'] = Problem.objects.all().count()
		context['num_hints'] = Hint.objects.all().count()
		context['lookup_url'] = reverse_lazy('arch-lookup', )
		return context


@login_required
def lookup(request: HttpRequest):
	if request.method == 'POST':
		form = ProblemSelectForm(request.POST)
		assert form.is_valid()
		problem = form.cleaned_data['problem']
		return HttpResponseRedirect(problem.get_absolute_url())
	else:
		return HttpResponseRedirect(reverse_lazy('arch-index', ))

arch/templates/arch/hint_confirm_delete.html
{% extends 'layout.html' %}
{% block title %}Delete {{ hint.number }}% Hint for {{ hint.problem }}{% endblock %}
{% block layout-content %}
{% include "generic-delete.html" %}
<hr />
<a href="{{ hint.get_absolute_url }}">&lt;&lt; Go back to hint</a>
<ul>
	<li>{{ hint.problem }}</li>
	<li>{{ hint.keywords }}</li>
	<li>{{ hint.content }}</li>
</ul>
{% endblock %}

arch/templates/arch/hint_detail.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}Hint {{ hint.number }}% for {{ hint.problem }}{% endblock %}

{% block layout-content %}
<p>Here is your hint:</p>
<div class="alert alert-info">
	{{ hint.content }}
</div>

<ul>
	<li><a href="{{ hint.problem.get_absolute_url }}">
			Back to <b>{{ hint.problem }}</b></a>
</ul>
<hr />
<ul>
	<li><a href="{% url "hint-create" hint.puid %}">Add another hint</a></li>
	<li><a href="{% url "hint-update" hint.puid hint.number %}">Update hint</a></li>
	<li><a href="{% url "hint-delete" hint.puid hint.number %}">Delete hint</a></li>
	</li>
	{% endblock %}

arch/templates/arch/hint_form.html
{% extends 'layout.html' %}
{% block title %}Create Hint{% endblock %}
{% block layout-content %}
{% include "generic-form.html" %}
<hr />
<p>All edits are tracked by timestamp and username,
	so if for some reason you need to rewind some edits,
	please contact a staff member for assistance.</p>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
	$(document).ready(function() {
		$("#id_problem").chosen({
			placeholder_text: "...",
			width: "90%",
			search_contains: true,
		});
	});
</script>
{% endblock %}

arch/templates/arch/hint_list.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}ARCH hints for {{ problem }}{% endblock %}

{% block layout-content %}

{% spaceless %}
<h1>{{ problem }}
	{% if problem.aops_url %}
	<a href="{{ problem.aops_url }}">(AOPS)</a>
	{% endif %}
</h1>
{% endspaceless %}
<p>
	<a href="{% url "wiki-problem" problem.puid %}">
		🎮 Get problem solution from the Wiki.
	</a>
</p>

{% if statement %}
<div class=" alert-secondary alert">
	{{ statement|safe }}
</div>
{% endif %}

<hr />

{% if hint_list %}
<p>The following hints are available for this problem.</p>
{% for hint in hint_list %}
<a href="{% url "hint-detail" hint.puid hint.number %}">
	<div class="alert alert-primary">
		<h2>Hint {{hint.number}}%</h2>
		{% if hint.keywords %}<i>Keywords</i>: {{ hint.keywords }}{% endif %}
	</div>
</a>
{% endfor %}
<p>Some of the hints may be pretty oblique
	or not apply to you.
	Remember, you can always ask the OTIS Discord or Evan
	for more personalized help!
</p>
{% else %}
<p><i>There aren't any hints here yet.
		If you've solved this problem,
		please help future students by
		<a href="{% url "hint-create" problem.puid %}">adding a hint</a></i>.</p>
</i>
{% endif %}


<ul>
	<li><a href="{% url "hint-create" problem.puid %}">Add hint</a></li>
	<li><a href="{% url "problem-update" problem.puid %}">Edit problem</a></li>
	<li><a href="{% url "problem-delete" problem.puid %}">Delete problem</a></li>
</ul>

{% endblock %}

arch/templates/arch/index.html
{% extends 'layout.html' %}
{% block title %}Arch{% endblock %}
{% block layout-content %}

Welcome to <strong>ARCH</strong>,
the Automated Repository of Canned Hints.
We hope you enjoy your visit.

<hr />

<div class="container row">
	<div class="col-6">
		<h2>Find problem</h2>

		<div class="mathjax_ignore">
			{% include "generic-form.html" with form=lookup_form target=lookup_url submit_name="Lookup" btn_class="btn-primary" %}
		</div>

	</div>
	<div class="col-6">
		<h2>New problem</h2>
		{% include "generic-form.html" with submit_name="Create" %}
	</div>
</div>

<hr />

<h2>Statistics</h2>
<p>
	As of {% now "D, d M Y" %}, ARCH has
	<ul>
		<li>{{ num_problems }} problems written</li>
		<li>{{ num_hints }} hints written</li>
	</ul>
	Add more hints to make ARCH more useful to other students!
</p>

<hr />

<h2>Discord integration</h2>

<ul>
	<li>In any channel, type <code>/grab 20IMO6</code>
		to pull the problem statement and a link to the ARCH entry.
		This works with any problem identifier.</li>
	<li>If you're not in a thread, you can omit the <code>/grab</code>
		and this will still work.</li>
	<li>Use <code>/active</code> to display the currently discussed problem.</li>
	<li>To add a hint for the currently discussed problem,
		just use <code>/hint [type content]</code>.
		Evil Chin will output a link to the newly created hint,
		where you can (if you choose) change the number and keywords.
		(By default, Evil Chin selects the smallest unused multiple of 10 for the number.)
	</li>
</ul>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
	$(document).ready(function() {
		$("#id_problem").chosen({
			placeholder_text: "...",
			width: "90%",
			search_contains: true,
		});
	});
</script>
{% endblock %}

arch/templates/arch/problem_confirm_delete.html
{% extends 'layout.html' %}
{% block title %}Delete {{ problem }}{% endblock %}
{% block layout-content %}
{% include "generic-delete.html" %}
<hr />
<a href="{% url "hint-list" problem.puid %}">&lt;&lt; Go back to problem</a>
<ul>
	<li><b>{{ problem.hint_set.count }} hints</b></li>
</ul>
{% endblock %}

arch/templates/arch/problem_form.html
{% extends 'layout.html' %}
{% block title %}Arch: Update {{ problem }}{% endblock %}
{% block layout-content %}

<h1>Update {{ problem }}</h1>
<p><a href="{{ problem.get_absolute_url }}">Back to problem.</a></p>

<hr />

{% include "generic-form.html" with submit_name="Update" %}

{% endblock %}